local map = vim.keymap.set

map('n', '<Space>', '<Nop>', { silent = true })
map('n', '<Leader>e', ':NvimTreeToggle<CR>', { desc = 'Toggle file tree' })
map('n', '<C-s>', ':write<CR>', { desc = 'Save file' })
map('i', '<C-s>', '<Esc>:write<CR>', { desc = 'Save file' })
map('n', '<Leader>w', ':write<CR>', { desc = 'Save file' })
map('n', '<Leader>q', ':q<CR>', { desc = 'Quit' })
map('n', '<Leader>h', ':nohlsearch<CR>', { desc = 'Clear search highlights' })
map('n', '<Tab>', ':bnext<CR>', { desc = 'Next buffer' })
map('n', '<S-Tab>', ':bprevious<CR>', { desc = 'Previous buffer' })
map('n', '<C-F4>', ':bd<CR>', { desc = 'Delete buffer' })
map('n', '<A-1>', ':buffer 1<CR>', { desc = 'Buffer 1' })
map('n', '<A-2>', ':buffer 2<CR>', { desc = 'Buffer 2' })
map('n', '<A-3>', ':buffer 3<CR>', { desc = 'Buffer 3' })
map('n', '<A-4>', ':buffer 4<CR>', { desc = 'Buffer 4' })
map('n', '<A-5>', ':buffer 5<CR>', { desc = 'Buffer 5' })

map('n', 'K', vim.lsp.buf.hover, { desc = 'LSP hover' })
map('n', 'gd', vim.lsp.buf.definition, { desc = 'Go to definition' })
map('n', 'gD', vim.lsp.buf.declaration, { desc = 'Go to declaration' })
map('n', 'gi', vim.lsp.buf.implementation, { desc = 'Go to implementation' })
map('n', 'gr', vim.lsp.buf.references, { desc = 'Find references' })
map('n', '<Leader>rn', vim.lsp.buf.rename, { desc = 'Rename symbol' })
map('n', '<Leader>ca', vim.lsp.buf.code_action, { desc = 'Code action' })
map('n', 'gl', vim.diagnostic.open_float, { desc = 'Show diagnostic' })
map('n', '[d', vim.diagnostic.goto_prev, { desc = 'Previous diagnostic' })
map('n', ']d', vim.diagnostic.goto_next, { desc = 'Next diagnostic' })
