local map = vim.keymap.set

map('n', '<Leader>e', ':NvimTreeToggle<CR>')
map('n', '<Leader>w', ':write<CR>')
map('n', '<Leader>q', ':q<CR>')
map('n', '<Leader>h', ':nohlsearch<CR>')
map('n', '<Tab>', ':bnext<CR>')
map('n', '<S-Tab>', ':bprevious<CR>')
map('n', '<C-F4>', ':bd<CR>')
map('n', '<A-1>', ':buffer 1<CR>')
map('n', '<A-2>', ':buffer 2<CR>')
map('n', '<A-3>', ':buffer 3<CR>')
map('n', '<A-4>', ':buffer 4<CR>')
map('n', '<A-5>', ':buffer 5<CR>')

map('n', 'K', vim.lsp.buf.hover)
map('n', 'gd', vim.lsp.buf.definition)
map('n', 'gD', vim.lsp.buf.declaration)
map('n', 'gi', vim.lsp.buf.implementation)
map('n', 'gr', vim.lsp.buf.references)
map('n', '<Leader>rn', vim.lsp.buf.rename)
map('n', '<Leader>ca', vim.lsp.buf.code_action)
map('n', 'gl', vim.diagnostic.open_float)
map('n', '[d', vim.diagnostic.goto_prev)
map('n', ']d', vim.diagnostic.goto_next)
